// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5c2-7JR_bPXYu2FPg-ZVMsq-7NZrSSBk',
    appId: '1:398176651975:web:ab2bc9ab16da98c77ccce2',
    messagingSenderId: '398176651975',
    projectId: 'premiertraslados-31ee2',
    authDomain: 'premiertraslados-31ee2.firebaseapp.com',
    storageBucket: 'premiertraslados-31ee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnX2ATEZtoZpEj31nzHeEYmkj_3bP5ass',
    appId: '1:398176651975:android:1062be70bafe95e37ccce2',
    messagingSenderId: '398176651975',
    projectId: 'premiertraslados-31ee2',
    storageBucket: 'premiertraslados-31ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsp5hj1G12EvKsZrb1YMSbGiGad0HRqM',
    appId: '1:398176651975:ios:d14abd64787da3a17ccce2',
    messagingSenderId: '398176651975',
    projectId: 'premiertraslados-31ee2',
    storageBucket: 'premiertraslados-31ee2.firebasestorage.app',
    iosBundleId: 'com.example.premiertrasladosAppchoferNuevo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsp5hj1G12EvKsZrb1YMSbGiGad0HRqM',
    appId: '1:398176651975:ios:d14abd64787da3a17ccce2',
    messagingSenderId: '398176651975',
    projectId: 'premiertraslados-31ee2',
    storageBucket: 'premiertraslados-31ee2.firebasestorage.app',
    iosBundleId: 'com.example.premiertrasladosAppchoferNuevo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2r523nuwRF3p70XFaQwXh1FaCqeeRWWI',
    appId: '1:398176651975:web:21146e69685530ce7ccce2',
    messagingSenderId: '398176651975',
    projectId: 'premiertraslados-31ee2',
    authDomain: 'premiertraslados-31ee2.firebaseapp.com',
    storageBucket: 'premiertraslados-31ee2.firebasestorage.app',
  );
}
